# .github/workflows/deploy.yml

name: Deploy Next.js to GitHub Pages

on:
  # Jalankan workflow ini setiap kali ada push ke branch 'main'
  push:
    branches: ["main"] # Ganti 'main' jika branch utama Anda adalah 'master'
  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions di GitHub
  workflow_dispatch:

# Atur izin untuk GITHUB_TOKEN agar bisa mendeploy ke GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Pilih versi Node.js yang sesuai dengan project Anda
          cache: "npm" # atau 'yarn'

      - name: Install dependencies
        run: npm install # atau 'yarn install'

      - name: Build project
        run: npm run build # atau 'yarn build'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload folder 'out' yang dihasilkan dari proses build
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
