# Nama workflow Anda
name: Deploy Next.js to GitHub Pages

# Kapan workflow ini akan berjalan
on:
  push:
    branches: ["main"] # Berjalan setiap kali ada push ke branch 'main'
  workflow_dispatch:

# Konfigurasi izin untuk workflow
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job untuk proses build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Sesuaikan dengan versi Node.js Anda
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Create .nojekyll file
        run: touch ./out/.nojekyll
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Folder yang akan di-upload

  # Job untuk proses deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Menunggu job 'build' selesai
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
